### ISSUE TITLE
Lingering pixels after update when using hardware DC pin

### ISSUE THREAD

**Issue by klaasdc** [vindar/tgx#27] opened 2024-09-13 15:28 UTC
I have a setup with soft DC pin that draws everything as it should. It has a menu system GUI, and I often draw animations where pages fly in from top or bottom of the screen. But when I swap the DC pin to a hardware capable one, I get some remaining pixels "dragging" along the pages. It is as if the last line of each page stays on the screen.
When I switch back to a soft DC, the issue disappears. I reproduce by just setting _hardware_dc to false at line 370 in ILI9341Driver.cpp.

```
        // _hardware_dc = _pspi->pinIsChipSelect(_dc);
        _hardware_dc = false;

        if (_hardware_dc)
```

The loss of hardware DC is not very important to me, the library is already very fast, but it seems very strange so I'd thought I'd report it.

**Comment by vindar** [comment] 2024-09-14 07:55
Hi,

Could you give me your exact wiring and a short sketch so that I can try to reproduce the problem ? Also, What SPI speed are you using and how long are the wires connecting the MCU to the screen ? Hardware DC toggles very fast so it needs really short wires at high speed.

I am closing the issue here because it belongs to the ILI9341_t4 repo and not TGX but please fell free to open a new one over there with a complete example of the issue and I will try to investigate further....

**Closed by vindar** 2024-09-14 07:55 UTC
